server:
  port: 8085
spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Hardik-kahar/MSConfigServer
          clone-on-start: true
          
          